### ISSUE TITLE
why are the filter fields ids and authors matched with prefixes?

### ISSUE THREAD

**Issue by quake** [rnostr/rnostr#10]
according to NIP-01, the filter fields ids and authors should be exact 32 bytes, I don't quite understand why rnostr filter them with a prefix match, am I misunderstanding something?

https://github.com/rnostr/rnostr/blob/f18c2d0e37e8a98fba58d5b195a54de253b8c3f1/db/src/filter.rs#L288-L289

https://github.com/rnostr/rnostr/blob/f18c2d0e37e8a98fba58d5b195a54de253b8c3f1/db/src/filter.rs#L40-L45

**Comment by arronzhang** [comment]
@quake  Previously nip01 suggested prefix matching, which was recently removed, [See changes](https://github.com/nostr-protocol/nips/commit/72bb8a128b2d7d3c2c654644cd68d0d0fe58a3b1#diff-39307f1617417657ee9874be314f13aabdc74401b124d0afe8217f2919c9c7d8L64). Glad to see it, I did some ugly looking logic in the db to support this. we can remove it.

**Comment by arronzhang** [comment]
@quake The scoping of kind ( between 0 and 65535) was also added at this point.

**Comment by quake** [comment]
> @quake Previously nip01 suggested prefix matching, which was recently removed, [See changes](https://github.com/nostr-protocol/nips/commit/72bb8a128b2d7d3c2c654644cd68d0d0fe58a3b1#diff-39307f1617417657ee9874be314f13aabdc74401b124d0afe8217f2919c9c7d8L64). Glad to see it, I did some ugly looking logic in the db to support this. we can remove it.

I see, found the related PR: https://github.com/nostr-protocol/nips/pull/703 , thanks for your information.
