### ISSUE TITLE
db export

### ISSUE THREAD

**Issue by rolikeusch** [rnostr/rnostr#2]
sorry for the next dumb question :(
i would like to test the export function, but i get always the message "_Error: error: Failed to create LMDB directory: Os { code: 17, kind: AlreadyExists, message: "File exists" }._" the file export.jsonl is not there, i can not find out which file is already there

this is the comman is use:
```./rnostr export /rnostr/data/events/data.mdb /rnostr/export.jsonl```

**Comment by arronzhang** [comment]
lmdb data is the directory. so the commad is `./rnostr export /rnostr/data/events /rnostr/export.jsonl`. I will fix the doc.

**Comment by rolikeusch** [comment]
ah, yes that way it works!
sorry i thought the path should be to the db :(

**Comment by rolikeusch** [comment]
with the above explanation from @arronzhang it works. so i close this issue.
